### PR TITLE
(SIMP-4941) Fix systemd fixtures

### PR DESCRIPTION
**Pull request by jeefberkey**
- Update systemd fixtures and CI assets
- Fix acceptance test by not testing text of failure code, only the exit
  code

SIMP-4941 #comment simp_openldap fixed

### CODE REVIEW

**Comment by jeefberkey** [comment]
https://gitlab.com/simp/pupmod-simp-simp_openldap/pipelines/23877374

**Comment by trevor-vaughan** [comment]
@jeannegreulich `auditd` does not appear to be used in the codebase so it can be removed from `metadata.json`.

We have to manually check each time because there is no guarantee that the tests have 100% coverage.

**Comment by jeefberkey** [comment]
it also looks like `sssd` is unused? and the `sssd` parameter is never used in code.

**Comment by jeefberkey** [comment]
https://gitlab.com/simp/pupmod-simp-simp_openldap/pipelines/24398143

**Comment by jeefberkey** [comment]
https://gitlab.com/simp/pupmod-simp-simp_openldap/pipelines/24400318

**Pull request merged**
